version: '2.4'
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      # - ADMIN_EMAIL=admin@localhost
      - TZ=Europe/Berlin
      # - WEBPASSWORD=password
    volumes:
      - pihole_config:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
    restart: unless-stopped
volumes:
  pihole_config:
  pihole_dnsmasq:
