version: '2.4'
services:
  pihole:
    container_name: nodered
    hostname: nodered
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - nodered_data:/data
    restart: unless-stopped
volumes:
  nodered_data:
