version: '2.4'
services:
  iobroker:
    restart: always
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    environment:
      - SETUID=1000
      - SETGID=1000
      - TZ=Europe/Berlin
      - IOB_ADMINPORT=8081
    ports:
      # WEB UI
      - 8081:8081
      # MQTT
      - 18830:1883
    volumes:
      - iobroker_config:/opt/iobroker
volumes:
  iobroker_config:
